'use strict';

// Feature-specific prototype behavior. Data is fictional and remains in this browser.
const STORAGE_KEY = 'bunjang-pokemon-prototype-v1';
const ME = '카드모으는중';
const catalog = [
  { id: 'p1', name: '포켓몬카드 151 피카츄 IR', code: '173/165 · 영문', image: 'pikachu.jpg', color: 'yellow', owner: '피카츄는못참지', role: '구매', date: '2026. 9. 8', price: '38,000원', count: 4, hearts: 24, mine: false },
  { id: 'p2', name: '포켓몬카드 151 꼬부기 IR', code: '170/165 · 영문', image: 'squirtle.png', color: 'blue', owner: '파도타는꼬부기', role: '판매', date: '2026. 9. 7', price: '32,000원', count: 8, hearts: 18, mine: false },
  { id: 'p3', name: '포켓몬카드 151 이상해씨 IR', code: '166/165 · 영문', image: 'bulbasaur.png', color: 'green', owner: ME, role: '구매', date: '2026. 9. 6', price: '29,000원', count: 3, hearts: 7, mine: true },
  { id: 'p4', name: '포켓몬카드 151 파이리 IR', code: '168/165 · 영문', image: 'charmander.png', color: 'yellow', owner: '주말의수집', role: '구매', date: '2026. 9. 5', price: '35,000원', count: 6, hearts: 12, mine: false },
  { id: 'p5', name: '포켓몬카드 151 꼬부기 IR', code: '170/165 · 영문', image: 'squirtle.png', color: 'blue', owner: ME, role: '판매', date: '2026. 8. 28', price: '30,000원', count: 3, hearts: 0, mine: true },
  { id: 'p6', name: '포켓몬카드 151 피카츄 IR', code: '173/165 · 영문', image: 'pikachu.jpg', color: 'yellow', owner: ME, role: '구매', date: '2026. 8. 21', price: '36,000원', count: 3, hearts: 0, mine: true },
];
catalog.forEach(p => { p.grading = '미감정'; p.condition = 'NM · 눈에 띄는 흠집 없음'; });
catalog.push(
  { ...catalog[0], id: 'p7', owner: '한칸씩채우기', date: '2026. 9. 3', price: '36,000원', count: 5, hearts: 0 },
  { ...catalog[0], id: 'p8', owner: '초록바인더', date: '2026. 9. 1', price: '27,000원', count: 7, hearts: 0, condition: 'LP · 뒷면 모서리 백화' }
);
catalog.push(...[{"id": "hit1", "name": "아르세우스 VSTAR UR", "code": "S12a 262/172 · 일문", "image": "hit-arceus.webp", "source": "https://kream.co.kr/products/652758", "series": "VSTAR 유니버스", "hit": true, "color": "yellow", "owner": "금빛바인더", "role": "구매", "date": "2026. 9. 14", "price": "150,000원", "count": 5, "hearts": 0, "mine": false, "grading": "미감정", "condition": "NM · 눈에 띄는 흠집 없음"}, {"id": "hit2", "name": "기라티나 VSTAR UR", "code": "S12a 261/172 · 일문", "image": "hit-giratina.webp", "source": "https://kream.co.kr/products/652757", "series": "VSTAR 유니버스", "hit": true, "color": "yellow", "owner": "반전세계", "role": "구매", "date": "2026. 9. 13", "price": "280,000원", "count": 6, "hearts": 0, "mine": false, "grading": "미감정", "condition": "NM · 눈에 띄는 흠집 없음"}, {"id": "hit3", "name": "리자몽 VSTAR SAR", "code": "S12a 212/172 · 일문", "image": "hit-charizard.webp", "source": "https://kream.co.kr/products/652708", "series": "VSTAR 유니버스", "hit": true, "color": "blue", "owner": "불꽃수집", "role": "구매", "date": "2026. 9. 12", "price": "100,000원", "count": 7, "hearts": 0, "mine": false, "grading": "미감정", "condition": "NM · 눈에 띄는 흠집 없음"}, {"id": "hit4", "name": "뮤츠 VSTAR SAR", "code": "S12a 221/172 · 일문", "image": "hit-mewtwo.webp", "source": "https://kream.co.kr/products/652717", "series": "VSTAR 유니버스", "hit": true, "color": "blue", "owner": "초능력한장", "role": "구매", "date": "2026. 9. 11", "price": "140,000원", "count": 8, "hearts": 0, "mine": false, "grading": "미감정", "condition": "NM · 눈에 띄는 흠집 없음"}]);
const seedPosts = [{"id": "s1", "author": "피카츄는못참지", "avatar": "피", "color": "", "count": 4, "role": "구매", "time": "12분 전", "topic": "자랑", "title": "151 피카츄 빈칸 드디어 채웠어요", "body": "팩에서 끝까지 안 나와서 결국 낱장으로 데려왔어요. 바인더에 한 칸 비어 있던 게 계속 신경 쓰였는데 이제 좀 편안하네요 ㅋㅋ 남은 건 리버스 홀로 몇 장… 이게 더 안 구해져요.", "product": "p1", "hearts": 24}, {"id": "s2", "author": "파도타는꼬부기", "avatar": "꼬", "color": "blue", "count": 8, "role": "거래", "time": "38분 전", "topic": "질문", "title": "영문 151 꼬부기, 번호 같으면 같은 카드인가요?", "body": "중복 꼬부기 정리하고 거래내역 보는데 같은 그림인데도 가격 차이가 꽤 나네요. 제 건 영문 170/165, 미감정이었어요. 검색에 뜨는 등급 카드랑은 따로 봐야 하는 거죠? 다음엔 뭘 맞춰서 찾아봐야 할까요?", "product": "p2", "hearts": 9}, {"id": "s3", "author": "주말의수집", "avatar": "주", "color": "green", "count": 6, "role": "거래", "time": "1시간 전", "topic": "일상", "title": "바인더 정리하다가 순서 또 바꿨어요", "body": "파이리 받아서 번호순으로 꽂았는데 진화 순서로 모아 두는 것도 예쁘더라고요. 프로모까지 넣으려니까 뒤쪽 자리가 애매해졌어요. 다들 프로모는 따로 빼 두시나요? 정리만 하다 주말 다 갔네요.", "product": "p4", "hearts": 16}];
const seedComments = {"s1": [{"id": "c1", "name": "주말의수집", "body": "저도 뒤로 갈수록 낱장으로 채웠어요. 같은 리버스만 계속 나오더라고요 ㅋㅋ", "time": "8분 전"}, {"id": "c2", "name": "파도타는꼬부기", "body": "남은 번호 적어두고 찾으니까 좀 낫더라고요. 한 장 배송비 때문에 몇 장씩 모아서 샀어요.", "time": "5분 전"}], "s2": [{"id": "c3", "name": "주말의수집", "body": "저는 언어랑 하단 번호 먼저 맞추고, 미감정끼리 봐요. 같은 번호여도 상태 다르면 가격은 따로 보게 되더라고요.", "time": "20분 전"}, {"id": "c5", "name": "피카츄는못참지", "body": "앞면만 말고 뒷면 모서리 사진도 받아보세요. 반사 심하면 옆에서 빛 주고 찍어달라고 했어요.", "time": "17분 전"}, {"id": "c6", "name": "파도타는꼬부기", "body": "아 제가 PSA 10까지 같이 보고 있었네요… 미감정으로 다시 찾아볼게요. 감사합니다!", "time": "14분 전"}], "s3": [{"id": "c7", "name": "피카츄는못참지", "body": "전 프로모는 뒤에 따로 뺐어요. 처음부터 자리 비워둘걸 계속 한 칸씩 밀고 있어요 ㅠ", "time": "45분 전"}], "p3": []};
function freshState() { return { version: 1, contentRevision: 2, posts: structuredClone(seedPosts), comments: structuredClone(seedComments), likes: [], shared: ['p3'], mode: 'normal', events: [] }; }
let state = freshState();
try { const saved = JSON.parse(localStorage.getItem(STORAGE_KEY)); if (saved?.version === 1 && Array.isArray(saved.posts) && saved.comments && Array.isArray(saved.shared)) state = saved; } catch { /* Storage can be unavailable in private/file previews. */ }
if (state.contentRevision !== 2) {
  state.posts = [...state.posts.filter(p => !['s1','s2','s3'].includes(p.id)), ...structuredClone(seedPosts)];
  for (const [id, rows] of Object.entries(seedComments)) {
    state.comments[id] = [...structuredClone(rows), ...(state.comments[id] || []).filter(c => !/^c\d+$/.test(c.id))];
  }
  state.contentRevision = 2;
}
let tab = 'stories', filter = '전체', productFilter = '전체', productView = 'grid', popular = false, modal = null, returnFocus = null, replyTo = null;
let draft = { title: '', body: '', topic: '자랑', product: null }, selectedTrade = null, selectedQuestion = null, toastTimer;
const dialog = document.querySelector('#dialog');
const panel = document.querySelector('#panel');
const escapeHTML = (s = '') => String(s).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]);
const product = id => catalog.find(p => p.id === id);
const post = id => state.posts.find(p => p.id === id);
const comments = id => state.comments[id] || [];
const sameCard = (a, b) => Boolean(a && b && a.name === b.name && a.code === b.code);
const sameCondition = (a,b) => sameCard(a,b) && a.grading === b.grading && a.condition === b.condition;
const tradeDate = p => { const [year,month,day] = p.date.split('.').map(Number); return Date.UTC(year,month-1,day); };
const visibleTrades = () => catalog.filter(p => !p.mine || state.shared.includes(p.id));
const relatedPosts = id => state.posts.filter(p => sameCard(product(p.product), product(id)));
const image = p => `assets/${p.image}`;
const uid = () => globalThis.crypto?.randomUUID?.() || `local-${Date.now()}-${Math.random().toString(16).slice(2)}`;
const icon = (name, cls = '') => `<img class="${cls}" src="assets/${name}.svg" alt="">`;
function persist() { try { localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); } catch { /* In-memory interactions still work. */ } }
function track(name, data = {}) { state.events.push({ name, ...data, at: new Date().toISOString() }); state.events = state.events.slice(-300); persist(); }
function toast(message) { const el = document.querySelector('#toast'); el.textContent = message; el.classList.add('show'); clearTimeout(toastTimer); toastTimer = setTimeout(() => el.classList.remove('show'), 2500); }
function header(title, trailing = '') { return `<header class="dialog-header"><h2 id="dialog-title">${escapeHTML(title)}</h2><div class="nav-actions">${trailing}<button class="icon-button" data-action="close" aria-label="닫기">${icon('close')}</button></div></header>`; }
function showDialog(content, nextModal) { if (!dialog.open) returnFocus = document.activeElement; modal = nextModal; dialog.innerHTML = content; if (!dialog.open) dialog.showModal(); dialog.scrollTop = 0; }
function closeDialog() { dialog.close(); modal = null; replyTo = null; returnFocus?.focus?.({ preventScroll: true }); }
function hasAccess() { if (state.mode !== 'ineligible') return true; showEligibility(); return false; }
function showEligibility() { showDialog(`${header('거래 경험으로 연결되는 공간')}<div class="dialog-body"><h3>포켓몬카드를 2회 이상 거래하면<br>함께 이야기할 수 있어요</h3><p>구매와 판매를 합쳐 2회 이상 거래한 사람들의 공간이에요. 지금은 1회 거래한 사용자 체험 상태예요.</p><div class="notice">체험 설정에서 3회 거래한 사용자로 바꿀 수 있어요.</div></div><div class="dialog-footer"><button class="ds-button" data-action="close">확인</button></div>`, { type: 'eligibility' }); }
function authorHTML(p) { return `<div class="author"><span class="avatar ${p.color || ''}">${escapeHTML(p.avatar || p.author?.slice(0, 1) || p.owner?.slice(0, 1))}</span><div class="author-info"><div class="author-line">${escapeHTML(p.author || p.owner)}<span class="experience">${escapeHTML(p.role)} ${p.count}회</span></div><div class="post-meta">${escapeHTML(p.time || p.date)}${p.topic ? ` · ${escapeHTML(p.topic)}` : ''}</div></div><button class="more" data-action="menu" data-id="${p.id}" aria-label="${escapeHTML(p.title || p.name)} 더보기">···</button></div>`; }
function attachedHTML(id, clickable = true) { const p = product(id); if (!p) return ''; const tag = clickable ? 'button' : 'div'; return `<${tag} class="attached" ${clickable ? `data-action="same-card" data-id="${id}"` : ''}> <img src="${image(p)}" alt="${escapeHTML(p.name)}"><div><div class="tag">${p.mine ? '내가' : '이야기 속'} ${p.role === '판매' ? '판매한' : '구매한'} 카드</div><strong>${escapeHTML(p.name)}</strong><small>${escapeHTML(p.date)} ${p.role} 완료 · ${escapeHTML(p.code)}</small>${clickable ? '<span class="attached-link">같은 카드 거래 보기</span>' : ''}</div>${icon('chevron-right', 'chevron')}</${tag}>`; }
function actionsHTML(id, hearts) { const liked = state.likes.includes(id); return `<div class="post-actions"><button class="reaction ${liked ? 'liked' : ''}" aria-pressed="${liked}" aria-label="좋아요 ${hearts + Number(liked)}" data-action="like" data-id="${id}">${icon(liked ? 'heart-filled' : 'heart')}<span>${hearts + Number(liked)}</span></button><button class="reaction" data-action="detail" data-id="${id}" aria-label="댓글 ${comments(id).length}개 보기">${icon('comment')}<span>${comments(id).length}</span></button></div>`; }
function storyHTML(p) { return `<article class="post" data-domain="CommunityStory" data-story-id="${p.id}">${authorHTML(p)}<button class="post-open" data-action="story" data-id="${p.id}"><h3 class="post-title">${escapeHTML(p.title)}</h3><p class="post-body preview">${escapeHTML(p.body)}</p></button>${p.product ? attachedHTML(p.product) : ''}${actionsHTML(p.id, p.hearts)}</article>`; }
function emptyHTML(title, body) { return `<section class="empty" data-domain="CommunityEmpty">${icon('talk')}<h3>${title}</h3><p>${body}</p><button class="ds-button small" data-action="compose">첫 이야기 남기기</button></section>`; }
function weeklyPromptHTML() { return `<button class="weekly-prompt" data-action="weekly-prompt"><span class="prompt-label">함께 이야기해요</span><strong>151 빈칸 채우기, 팩 vs 낱장?</strong><small>끝까지 안 나오는 한 장, 어떻게 구하셨나요?</small>${icon('chevron-right')}</button>`; }
function productCardHTML(p) { const storyCount=relatedPosts(p.id).length; return `<article class="product-card" data-domain="TradedCard"><button class="product-visual ${p.color}" data-action="product" data-id="${p.id}" aria-label="${escapeHTML(p.name)} 거래 정보 보기"><span class="product-status">${p.hit ? 'HIT · ' : ''}${p.mine ? '내 ' : ''}${p.role} 완료</span><img src="${image(p)}" alt="${escapeHTML(p.name)} ${escapeHTML(p.code)}"></button><p class="product-price">${escapeHTML(p.price)}</p><button class="product-name" data-action="product" data-id="${p.id}">${escapeHTML(p.name)}</button><p class="product-sub">거래일자 ${escapeHTML(p.date)}</p><div class="product-card-actions">${p.mine ? `<button class="trade-story-link" data-action="trade-story" data-id="${p.id}">이 거래로 이야기 쓰기</button>` : storyCount ? `<button class="trade-story-link neutral" data-action="related-stories" data-id="${p.id}">이 카드 이야기 ${storyCount}</button>` : ''}<button class="similar-link" data-action="similar" data-id="${p.id}">비슷한 상품 보기 ${icon('chevron-right')}</button></div></article>`; }
function renderStories() { let list = state.mode === 'empty' ? state.posts.filter(p => p.author === ME) : [...state.posts]; if (filter !== '전체') list = list.filter(p => p.topic === filter); if (popular) list.sort((a,b) => b.hearts - a.hearts); return `<section data-component="Section">${state.mode === 'normal' ? weeklyPromptHTML() : ''}<div class="filter-row">${['전체','자랑','질문','일상'].map(t => `<button class="chip ${filter === t ? 'active' : ''}" aria-pressed="${filter === t}" data-filter="${t}">${t}</button>`).join('')}<button class="sort" data-action="sort">${popular ? '공감순' : '최신순'}${icon('chevron-down')}</button></div>${list.length ? list.map(storyHTML).join('') : emptyHTML(filter === '전체' ? '첫 이야기를 기다리고 있어요' : `아직 ${filter} 이야기가 없어요`, '좋아하는 카드 한 장, 짧은 한마디부터 시작해요.')}</section>`; }
function viewControlsHTML() {
  return `<div class="view-controls" role="group" aria-label="거래 상품 보기 방식">${[['grid','상품 보기'],['history','거래내역']].map(([value,label]) => `<button data-product-view="${value}" aria-pressed="${productView === value}" class="${productView === value ? 'active' : ''}">${label}</button>`).join('')}</div>`;
}
function historyHTML(list) {
  return `<div class="trade-history">${list.map(p => {
    const count = list.filter(other => sameCondition(p,other)).length;
    return `<article class="history-row" data-trade-id="${p.id}"><button class="history-image" data-action="product" data-id="${p.id}" aria-label="${escapeHTML(p.name)} 거래 정보"><img src="${image(p)}" alt="${escapeHTML(p.name)}"></button><div class="history-content"><button class="history-open" data-action="product" data-id="${p.id}"><span class="history-date">${escapeHTML(p.date)} · ${p.mine ? '내 ' : ''}${p.role} 완료</span><strong>${p.hit ? '<span class="hit-label">HIT</span>' : ''}${escapeHTML(p.name.replace('포켓몬카드 ',''))}</strong><span class="history-meta">${escapeHTML(p.code)} · ${escapeHTML(p.grading)}</span><span class="history-meta">${escapeHTML(p.condition)}</span><b class="history-price">${escapeHTML(p.price)}</b></button><button class="history-related" data-action="same-card" data-id="${p.id}" aria-label="동일 조건 ${count}건 · 카드 거래 보기"><span>동일 조건 <strong>${count}건</strong></span><span class="history-related-action">거래 보기 ${icon('chevron-right')}</span></button></div></article>`;
  }).join('')}</div>`;
}
function renderProducts() { let list = visibleTrades().sort((a,b) => tradeDate(b)-tradeDate(a)); if (productFilter === 'HIT') list = list.filter(p => p.hit); if (productFilter === '내 거래') list = list.filter(p => p.mine); if (state.mode === 'empty') list = list.filter(p => p.mine && state.shared.includes(p.id)); return `<section data-component="Section">${viewControlsHTML()}<div class="filter-row">${['전체','내 거래','HIT'].map(t => `<button class="chip ${productFilter === t ? 'active' : ''}" aria-pressed="${productFilter === t}" data-product-filter="${t}">${t}</button>`).join('')}<span class="sort">${list.length}개의 거래 상품</span></div><p class="trade-summary">${productFilter === 'HIT' ? '컬렉터가 찾는 HIT 카드만 모았어요.' : productView === 'history' ? '최근 완료 거래예요. 동일 조건끼리 건수를 모았어요.' : '우리 사이를 오간 카드를 구경해보세요.'}<small>${productFilter === 'HIT' ? 'KREAM HIT 선정 참고 · 가격·거래는 가상 예시' : '샘플 데이터 · 상태는 판매자 기재 기준'}</small></p>${productView === 'grid' ? `<div class="product-grid">${list.map(productCardHTML).join('')}</div>` : historyHTML(list)}${!list.length ? `<div class="empty"><h3>함께 볼 카드를 기다리고 있어요</h3><p>내 거래에서 공개할 카드를 골라보세요.</p><button class="ds-button small" data-action="my-trades">내 거래 보기</button></div>` : ''}</section>`; }
function renderPanel() { panel.innerHTML = state.mode === 'ineligible' ? `<section class="empty"><h3>거래 경험이 쌓이면 연결돼요</h3><p>포켓몬카드 구매·판매 합산 2회부터<br>같은 취향의 사람들과 함께할 수 있어요.</p><button class="ds-button small" data-action="connection">내 연결 조건 보기</button></section>` : tab === 'stories' ? renderStories() : renderProducts(); const fab = document.querySelector('.write-fab'); fab.setAttribute('aria-label', tab === 'stories' ? '이야기 쓰기' : '내 거래 나누기'); document.querySelector('#connection-text').innerHTML = state.mode === 'ineligible' ? '포켓몬카드 <strong>1회 거래</strong> · 2회부터 연결돼요' : '<strong>3번의 거래로 연결된 포켓몬카드 취향</strong><small>내 거래에서 함께 볼 카드를 골라보세요.</small>'; }
function switchTab(next) { tab = next; document.querySelectorAll('[data-tab]').forEach(b => { const active = b.dataset.tab === tab; b.setAttribute('aria-selected',String(active)); b.tabIndex = active ? 0 : -1; }); panel.setAttribute('aria-labelledby',`tab-${tab}`); renderPanel(); track('tab_view',{tab}); }
function commentsHTML(id) { const all = comments(id); return `<h3 class="comment-heading">함께 나눈 이야기 ${all.length}</h3><div class="comment-list">${all.length ? all.map(c => `<div class="comment ${c.replyTo ? 'reply' : ''}"><span class="avatar ${c.name === ME ? 'pink' : 'blue'}">${escapeHTML(c.name.slice(0,1))}</span><div class="comment-content"><div class="comment-name">${escapeHTML(c.name)}${c.name === ME ? ' · 나' : ''}</div><p class="comment-text">${c.replyTo ? `<strong>@${escapeHTML(c.replyTo)}</strong> ` : ''}${escapeHTML(c.body)}</p><button class="reply-action" data-action="reply" data-id="${id}" data-name="${escapeHTML(c.name)}">답글 달기</button></div></div>`).join('') : '<p class="empty-comments">첫 반응이나 질문을 남겨보세요.</p>'}</div>`; }
function commentFooter(id) { return `<div class="dialog-footer composer-footer"><div class="reply-target" ${replyTo ? '' : 'hidden'}><span>${escapeHTML(replyTo || '')}님에게 답글</span><button data-action="cancel-reply">취소</button></div><form class="comment-form" data-comment-id="${id}"><input name="comment" aria-label="댓글 입력" placeholder="같은 취향에 한마디 남겨보세요" maxlength="500" required autocomplete="off"><button class="ds-button small" type="submit">등록</button></form></div>`; }
function showStory(id) { const p = post(id); if (!p) return; replyTo = null; showDialog(`${header('이야기')}<div class="dialog-body"><article class="post">${authorHTML(p)}<h3 class="post-title">${escapeHTML(p.title)}</h3><p class="post-body">${escapeHTML(p.body)}</p>${p.photo && product(p.product) ? `<div class="photo-stage"><img src="${image(product(p.product))}" alt="${escapeHTML(product(p.product).name)}"></div>` : ''}${p.product ? attachedHTML(p.product) : ''}${actionsHTML(p.id,p.hearts)}</article>${commentsHTML(id)}</div>${commentFooter(id)}`,{type:'story',id}); track('story_open',{id}); }
function showProduct(id) { const p = product(id); if (!p) return; replyTo = null; showDialog(`${header('카드에 이어지는 이야기')}<div class="dialog-body"><div class="detail-image"><img src="${image(p)}" alt="${escapeHTML(p.name)} ${escapeHTML(p.code)}"></div><p class="product-price">${escapeHTML(p.price)}</p><span class="eyebrow">${p.role} 완료한 카드 · ${p.date}</span><h3 class="detail-title">${escapeHTML(p.name)}</h3>${p.hit ? `<p class="hit-source">HIT · ${escapeHTML(p.series)}<br><a href="${escapeHTML(p.source)}" target="_blank" rel="noopener noreferrer">카드 정보·이미지 출처: KREAM ${icon('chevron-right')}</a><small>가격·거래일·상태는 프로토타입용 가상 데이터예요.</small></p>` : ''}<p class="detail-context">${escapeHTML(p.code)} · ${escapeHTML(p.grading)} · ${escapeHTML(p.condition)} · ${p.mine ? '내 거래' : escapeHTML(p.owner)+'님의 거래'}</p>${actionsHTML(id,p.hearts)}<div class="notice">과거 거래한 카드예요. 현재 보유 여부나 판매 계획은 달라질 수 있어요.</div><button class="my-trades-link" data-action="question" data-id="${id}"><strong>거래해 본 사람에게 물어보기</strong>${icon('chevron-right')}</button>${p.mine ? `<button class="my-trades-link" data-action="trade-story" data-id="${id}"><strong>이 거래로 이야기 쓰기</strong>${icon('chevron-right')}</button>` : ''}${relatedStoriesHTML(id)}${commentsHTML(id)}</div>${commentFooter(id)}`,{type:'product',id}); track('transaction_open',{id}); }
function showCompose(keepDraft=false) { if (!hasAccess()) return; if (!keepDraft) draft={title:'',body:'',topic:'자랑',product:null,source:'feed'}; if(!keepDraft)track('compose_started',{source:'feed'}); showDialog(`${header('이야기 쓰기')}<form id="post-form"><div class="dialog-body"><span class="eyebrow">포켓몬카드 · 같은 취향의 사람들에게</span><div class="compose-topics">${['자랑','질문','일상'].map(t=>`<button type="button" class="chip ${draft.topic===t?'active':''}" data-topic="${t}" aria-pressed="${draft.topic===t}">${t}</button>`).join('')}</div><input class="compose-input title" name="title" aria-label="이야기 제목" placeholder="어떤 이야기를 나눌까요?" maxlength="80" value="${escapeHTML(draft.title)}" required><textarea class="compose-input body" name="body" aria-label="이야기 내용" placeholder="좋아하는 이유도, 궁금한 것도 좋아요.\n카드 한 장에서 이야기를 시작해보세요." maxlength="1000" required>${escapeHTML(draft.body)}</textarea><p class="character-count"><span id="character-count">${draft.body.length}</span> / 1,000</p>${draft.product ? `${attachedHTML(draft.product,false)}<button type="button" class="remove-attachment" data-action="remove-attachment">거래 카드 빼기</button>` : `<button type="button" class="attach-button" data-action="attach">${icon('plus')}내 거래에서 카드 붙이기 <span class="post-meta">선택</span></button>`}<p class="section-help" style="margin-top:12px">${draft.product ? '첨부한 카드의 상품 정보와 나의 거래 경험이 함께 보여요.' : '사진을 새로 찍지 않아도 괜찮아요.'}</p></div><div class="dialog-footer"><button id="publish" class="ds-button" type="submit" ${draft.title.trim()&&draft.body.trim()?'':'disabled'}>이야기 올리기</button></div></form>`,{type:'compose'}); }
function startTradeStory(id) {
  if (!hasAccess()) return;
  const trade = product(id);
  if (!trade?.mine) return;
  draft = { title: '', body: '', topic: '자랑', product: id, source: 'transaction' };
  showCompose(true);
  track('compose_started', { source: 'transaction', product_id: id });
}
function relatedStoriesHTML(id) {
  const list = relatedPosts(id);
  return `<section class="related-stories"><h3>이 카드가 언급된 이야기 <span>${list.length}</span></h3>${list.length ? list.map(p => `<button class="related-story" data-action="story" data-id="${p.id}"><strong>${escapeHTML(p.title)}</strong><small>${escapeHTML(p.topic)} · ${escapeHTML(p.author)}</small></button>`).join('') : '<p class="section-help">아직 이 카드가 담긴 이야기가 없어요.</p>'}</section>`;
}
function showRelatedStories(id) {
  showDialog(`${header('이 카드 이야기')}<div class="dialog-body">${relatedStoriesHTML(id)}</div>`, { type: 'related-stories', id });
  track('related_stories_open', { product_id: id });
}
function showSameCard(id) {
  const source = product(id);
  if (!source) return;
  const list = visibleTrades().filter(p => sameCard(source, p));
  showDialog(`${header('같은 카드 거래')}<div class="dialog-body"><h3>${escapeHTML(source.name)}</h3><p class="section-help">${escapeHTML(source.code)} · 공개된 완료 거래 ${list.length}건</p><p class="notice">샘플 거래 · 등급과 상태가 다른 거래는 가격 비교 시 구분해서 봐주세요.</p>${list.map(p => `<button class="trade-choice" data-action="product" data-id="${p.id}"><img src="${image(p)}" alt="${escapeHTML(p.name)}"><span class="choice-text"><strong>${escapeHTML(p.price)}</strong><small>${p.mine ? '내 ' : ''}${p.role} 완료 · ${escapeHTML(p.date)}</small><small>${escapeHTML(p.grading)} · ${escapeHTML(p.condition)}</small></span>${icon('chevron-right')}</button>`).join('') || '<p class="notice">현재 공개된 같은 카드 거래가 없어요.</p>'}${relatedStoriesHTML(id)}</div>`, { type: 'same-card', id });
  track('same_card_trades_open', { product_id: id, count: list.length });
}
function captureDraft() { const f=document.querySelector('#post-form'); if(f){draft.title=f.elements.title.value;draft.body=f.elements.body.value;} }
function showTradePicker() { captureDraft(); selectedTrade=draft.product; showDialog(`${header('내 거래에서 카드 붙이기')}<div class="dialog-body"><p>이야기에 담고 싶은 카드를 골라주세요.</p>${catalog.filter(p=>p.mine).map(p=>`<button class="trade-choice ${selectedTrade===p.id?'selected':''}" data-action="select-trade" data-id="${p.id}"><img src="${image(p)}" alt="${escapeHTML(p.name)}"><span class="choice-text"><strong>${escapeHTML(p.name)}</strong><small>${p.date} ${p.role} 완료</small></span><span class="choice-indicator"></span></button>`).join('')}</div><div class="dialog-footer"><button class="ds-button secondary" data-action="back-compose">돌아가기</button><button class="ds-button" id="attach-confirm" data-action="confirm-attach" ${selectedTrade?'':'disabled'}>이 카드 붙이기</button></div>`,{type:'picker'}); }
function showMyTrades() { if(!hasAccess())return; showDialog(`${header('내 거래 나누기')}<div class="dialog-body"><h3>내 거래에서 함께 볼 카드를 골라주세요</h3><p>포켓몬카드를 구매·판매한 경험이 2회 이상이면 이 공간에 연결돼요. 내 거래는 구매 2회·판매 1회예요.</p><p>공개한 카드만 거래 상품 탭에 보여요. 거래 상대방은 공개하지 않아요. 상품명·거래 금액·거래일은 함께 보여요.</p>${catalog.filter(p=>p.mine).map(p=>`<div class="trade-choice"><img src="${image(p)}" alt="${escapeHTML(p.name)}"><div class="choice-text"><strong>${escapeHTML(p.name)}</strong><small>${p.date} ${p.role} 완료</small></div><label class="toggle-row"><span class="sr-label">공개</span><input type="checkbox" data-share-id="${p.id}" aria-label="${escapeHTML(p.name)} 거래 공개" ${state.shared.includes(p.id)?'checked':''}></label></div>`).join('')}<div class="notice">공개 설정은 언제든 바꿀 수 있어요. 글에 직접 붙인 카드는 해당 글에서 따로 관리해요.</div></div><div class="dialog-footer"><button class="ds-button" data-action="finish-share">완료</button></div>`,{type:'my-trades'}); }
function showQuestion(id) { if(!hasAccess())return; const p=product(id);selectedQuestion=null;const intentions=p.role==='구매'?['아직 가지고 계시면 판매 계획이 있나요?','이 카드를 다시 구매할 생각이 있나요?']:['이 카드를 다시 구매할 생각이 있나요?'];showDialog(`${header('이 카드에 대해 물어보기')}<div class="dialog-body">${attachedHTML(id,false)}<p style="margin-top:16px">어떤 점이 궁금하세요?</p><div class="question-options">${[...intentions,'수집·보관 경험을 물어보고 싶어요'].map(q=>`<button data-question="${escapeHTML(q)}">${escapeHTML(q)}</button>`).join('')}</div><label class="form-label" for="question-text">내 질문</label><textarea id="question-text" class="compose-input body" style="min-height:100px;border:1px solid var(--line);border-radius:6px;padding:12px" maxlength="500" placeholder="궁금한 점을 남겨주세요"></textarea><p class="section-help">이 카드의 이야기로 공개돼요. 거래 예약이나 구매 요청은 아니에요.</p></div><div class="dialog-footer"><button class="ds-button" id="question-submit" data-action="submit-question" data-id="${id}" disabled>질문 남기기</button></div>`,{type:'question',id}); }
function showSimilar(id) { const source=product(id); const keyword=source.name.split(' ').at(-2); const related=visibleTrades().filter(p=>p.id!==id&&p.name.includes(keyword)).slice(0,2); const matches=related.length?related:visibleTrades().filter(p=>p.id!==id).slice(0,2); showDialog(`${header('비슷한 상품')}<div class="dialog-body"><p><strong>${escapeHTML(source.name)}</strong>과 비슷한 완료 거래예요.</p>${matches.map(p=>`<button class="trade-choice" data-action="product" data-id="${p.id}"><img src="${image(p)}" alt="${escapeHTML(p.name)}"><span class="choice-text"><strong>${escapeHTML(p.price)}</strong><small>${escapeHTML(p.name)} · 거래일자 ${escapeHTML(p.date)}</small></span>${icon('chevron-right')}</button>`).join('')}<div class="notice">프로토타입에서는 같은 시리즈의 완료 거래를 예시로 보여줘요.</div></div>`,{type:'similar',id}); track('similar_products_open',{id}); }
function showActivity() { if(!hasAccess())return; document.querySelector('.notification-dot').hidden=true; const visible=state.shared.includes('p3');showDialog(`${header('내 반응 소식')}<div class="dialog-body">${visible?`<button class="activity-row" data-action="product" data-id="p3"><img src="${image(product('p3'))}" alt="이상해씨"><div><p><strong>피카츄는못참지</strong>님이 내 거래 카드에 이야기를 남겼어요.</p><small>“이상해씨 표정이 너무 평온해서…” · 10분 전</small></div></button><button class="activity-row" data-action="product" data-id="p3"><img src="${image(product('p3'))}" alt="이상해씨"><div><p>내가 거래한 <strong>이상해씨</strong> 카드에 7명이 공감했어요.</p><small>포켓몬카드 · 샘플 반응</small></div></button>`:'<div class="empty"><h3>아직 새 반응이 없어요</h3><p>내 거래나 이야기를 나누면 이곳에서 소식을 볼 수 있어요.</p></div>'}</div>`,{type:'activity'});track('activity_open'); }
function showAbout(connection=false){if(connection&&state.mode==='ineligible'){showEligibility();return;}showDialog(`${header(connection?'이 공간에 연결된 이유':'포켓몬카드 커뮤니티')}<div class="dialog-body"><h3>좋아하는 카드가<br>우리를 모이게 했어요</h3><p>포켓몬카드를 구매하거나 판매한 경험이 2회 이상인 사람들이 함께하는 공간이에요. 따로 가입하지 않아도 거래 경험으로 연결돼요.</p><div class="notice">내 거래는 구매 2회 · 판매 1회예요.<br>거래 이력 공개는 ‘내 거래 나누기’에서 직접 고를 수 있어요.</div><p style="margin-top:16px">카드를 구경하고, 마음에 드는 점을 표현하고, 경험을 나눠보세요. 거래 경력이 전문성이나 정품을 보증하지는 않아요.</p></div><div class="dialog-footer"><button class="ds-button" data-action="close">함께 구경하기</button></div>`,{type:'about'});}
function showDemo(){showDialog(`${header('체험 설정')}<div class="dialog-body"><p class="demo-meta">가상의 이용자·거래·반응을 사용한 로컬 프로토타입이에요. 입력 내용은 이 브라우저에만 저장돼요.</p><div class="demo-options">${[['normal','3회 거래한 사용자 · 기본 커뮤니티'],['empty','처음 생긴 공간 · 콘텐츠가 적은 상태'],['ineligible','1회 거래한 사용자 · 연결 전']].map(([value,label])=>`<label><input type="radio" name="demo-mode" value="${value}" ${state.mode===value?'checked':''}>${label}</label>`).join('')}</div><p class="demo-meta">첫 화면은 이야기 탭이에요. 내 반응 소식에서 반응을 받은 거래 카드로 이동할 수 있어요.</p><button class="ds-button outline" data-action="reset-confirm">체험 내용 초기화</button></div><div class="dialog-footer"><button class="ds-button" data-action="close">체험 계속하기</button></div>`,{type:'demo'});}
function showMenu(id){const p=post(id)||product(id);if(!p)return;const mine=p.author===ME||p.mine;showDialog(`${header('콘텐츠 관리')}<div class="dialog-body"><div class="question-options">${mine&&post(id)?`<button data-action="delete-post" data-id="${id}">내 이야기 삭제</button>`:mine?'<button data-action="my-trades">내 거래 공개 관리</button>':`<button data-action="report" data-id="${id}">이 콘텐츠 신고하기</button>`}</div></div>`,{type:'menu',id});}

document.addEventListener('click',event=>{
  const b=event.target.closest('button');if(!b||b.disabled)return;
  if(b.dataset.tab){switchTab(b.dataset.tab);return;}
  if(b.dataset.filter){filter=b.dataset.filter;renderPanel();return;}
  if(b.dataset.productView){productView=b.dataset.productView;renderPanel();document.querySelector(`[data-product-view="${productView}"]`).focus();track('product_view_changed',{view:productView});return;}
  if(b.dataset.productFilter){productFilter=b.dataset.productFilter;renderPanel();return;}
  if(b.dataset.topic){captureDraft();draft.topic=b.dataset.topic;showCompose(true);return;}
  if(b.dataset.question){selectedQuestion=b.dataset.question;document.querySelectorAll('[data-question]').forEach(q=>q.classList.toggle('selected',q===b));const field=document.querySelector('#question-text');field.value=selectedQuestion==='수집·보관 경험을 물어보고 싶어요'?'':selectedQuestion;document.querySelector('#question-submit').disabled=!field.value.trim();field.focus();return;}
  const id=b.dataset.id;
  switch(b.dataset.action){
    case 'close': if(modal?.type==='picker'){showCompose(true);}else closeDialog();break;
    case 'about':showAbout();break;
    case 'connection':state.mode==='ineligible'?showEligibility():showMyTrades();break;
    case 'activity':showActivity();break;
    case 'sort':popular=!popular;renderPanel();break;
    case 'compose':tab==='products'?showMyTrades():showCompose();break;
    case 'story':if(hasAccess())showStory(id);break;
    case 'product':if(hasAccess())showProduct(id);break;
    case 'trade-story':startTradeStory(id);break;
    case 'same-card':if(hasAccess())showSameCard(id);break;
    case 'related-stories':if(hasAccess())showRelatedStories(id);break;
    case 'weekly-prompt':if(hasAccess()){draft={title:'151 빈칸 채우기, 팩 vs 낱장?',body:'',topic:'자랑',product:null,source:'weekly-prompt'};showCompose(true);track('compose_started',{source:'weekly-prompt'});}break;
    case 'detail':if(hasAccess())post(id)?showStory(id):showProduct(id);break;
    case 'like':{if(!hasAccess())break;state.likes=state.likes.includes(id)?state.likes.filter(x=>x!==id):[...state.likes,id];track('reaction_toggle',{id,liked:state.likes.includes(id)});renderPanel();if(dialog.open&&modal?.id===id){const oldScroll=dialog.scrollTop;modal.type==='story'?showStory(id):showProduct(id);dialog.scrollTop=oldScroll;}break;}
    case 'reply':replyTo=b.dataset.name;{const row=document.querySelector('.reply-target');row.hidden=false;row.querySelector('span').textContent=replyTo+'님에게 답글';document.querySelector('.comment-form input').focus();}break;
    case 'cancel-reply':replyTo=null;document.querySelector('.reply-target').hidden=true;break;
    case 'attach':showTradePicker();break;
    case 'back-compose':showCompose(true);break;
    case 'select-trade':selectedTrade=id;document.querySelectorAll('.trade-choice').forEach(c=>c.classList.toggle('selected',c.dataset.id===id));document.querySelector('#attach-confirm').disabled=false;break;
    case 'confirm-attach':draft.product=selectedTrade;showCompose(true);break;
    case 'remove-attachment':captureDraft();draft.product=null;showCompose(true);break;
    case 'my-trades':showMyTrades();break;
    case 'finish-share':closeDialog();switchTab('products');toast('내 거래 공개 설정을 저장했어요');break;
    case 'question':showQuestion(id);break;
    case 'similar':showSimilar(id);break;
    case 'submit-question':{const body=document.querySelector('#question-text').value.trim();if(!body)break;(state.comments[id]??=[]).push({id:uid(),name:ME,body,time:'방금'});track('question_posted',{id,kind:selectedQuestion||'custom'});showProduct(id);renderPanel();break;}
    case 'demo':showDemo();break;
    case 'reset-confirm':showDialog(`${header('체험 내용을 초기화할까요?')}<div class="dialog-body"><p>이 브라우저에서 작성한 글과 댓글, 반응, 공개 설정을 지우고 처음 샘플로 돌아가요.</p></div><div class="dialog-footer"><button class="ds-button secondary" data-action="demo">돌아가기</button><button class="ds-button" data-action="reset">초기화</button></div>`,{type:'reset'});break;
    case 'reset':state=freshState();persist();filter='전체';productFilter='전체';productView='grid';popular=false;closeDialog();switchTab('stories');toast('처음 체험 상태로 돌아왔어요');break;
    case 'menu':showMenu(id);break;
    case 'report':showDialog(`${header('콘텐츠 신고')}<div class="dialog-body"><p>어떤 점이 불편했나요?</p><div class="question-options">${['불쾌한 표현','광고·도배','잘못된 정보'].map(t=>`<button data-action="report-done">${t}</button>`).join('')}</div><p class="section-help">프로토타입에서는 실제 신고가 전송되지 않아요.</p></div>`,{type:'report'});break;
    case 'report-done':closeDialog();toast('신고 흐름 체험을 완료했어요');break;
    case 'delete-post':state.posts=state.posts.filter(p=>p.id!==id);delete state.comments[id];track('story_deleted',{id});closeDialog();renderPanel();toast('이야기를 삭제했어요');break;
  }
});
document.addEventListener('input',event=>{if(event.target.closest('#post-form')){captureDraft();document.querySelector('#character-count').textContent=draft.body.length;document.querySelector('#publish').disabled=!(draft.title.trim()&&draft.body.trim());}if(event.target.id==='question-text')document.querySelector('#question-submit').disabled=!event.target.value.trim();});
document.addEventListener('change',event=>{const el=event.target;if(el.dataset.shareId){const id=el.dataset.shareId;state.shared=el.checked?[...new Set([...state.shared,id])]:state.shared.filter(x=>x!==id);track('transaction_share_changed',{id,shared:el.checked});renderPanel();}if(el.name==='demo-mode'){state.mode=el.value;persist();renderPanel();}});
document.addEventListener('submit',event=>{event.preventDefault();if(!hasAccess())return;const f=event.target;if(f.id==='post-form'){captureDraft();if(!draft.title.trim()||!draft.body.trim())return;const p={id:uid(),author:ME,avatar:'나',color:'pink',count:3,role:'거래',time:'방금',topic:draft.topic,title:draft.title.trim(),body:draft.body.trim(),product:draft.product,hearts:0};state.posts.unshift(p);track('story_published',{id:p.id,attached:Boolean(p.product),topic:p.topic,product_id:p.product,source:draft.source||'feed'});closeDialog();filter='전체';popular=false;switchTab('stories');window.scrollTo({top:0,behavior:'smooth'});toast('포켓몬카드 공간에 이야기를 남겼어요');}else if(f.dataset.commentId){const body=f.elements.comment.value.trim();if(!body)return;const id=f.dataset.commentId;(state.comments[id]??=[]).push({id:uid(),name:ME,body,time:'방금',replyTo});track('comment_posted',{id,reply:Boolean(replyTo)});post(id)?showStory(id):showProduct(id);renderPanel();document.querySelector('.comment-form input').focus();}});
dialog.addEventListener('cancel',()=>{modal=null;replyTo=null;returnFocus?.focus?.({preventScroll:true});});
dialog.addEventListener('click',event=>{if(event.target===dialog){const r=dialog.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)closeDialog();}});
document.querySelector('.tabs').addEventListener('keydown',event=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(event.key))return;event.preventDefault();const next=event.key==='Home'?'stories':event.key==='End'?'products':tab==='stories'?'products':'stories';switchTab(next);document.querySelector(`[data-tab="${next}"]`).focus();});
let touchStart=null;
panel.addEventListener('touchstart',e=>{if(e.touches.length!==1||e.target.closest('button,input,textarea'))return;const t=e.touches[0];if(t.clientX<24)return;touchStart={x:t.clientX,y:t.clientY};},{passive:true});
panel.addEventListener('touchend',e=>{if(!touchStart)return;const t=e.changedTouches[0],dx=t.clientX-touchStart.x,dy=t.clientY-touchStart.y;touchStart=null;if(Math.abs(dx)>75&&Math.abs(dx)>Math.abs(dy)*1.8)switchTab(dx<0?'products':'stories');},{passive:true});
renderPanel();track('community_view',{tab,mode:state.mode});
